### ISSUE TITLE
"NumberFormatException: null" When "CountingBloomFilter.getEstimatedCount" is called before an "add"

### ISSUE THREAD

**Issue by JPercivall** [Baqend/Orestes-Bloomfilter#40]
I am working to add Bloom filter support to Apache NiFi[1] using this library and ran across this corner case when unit testing. The steps to reproduce:

1. Initialize a new Redis backed CountingBloomFilter 
2. Call CountingBloomFilter countingBloomFilter.getEstimatedCount()
3. This leads to the Stack trace listed at the end (most of this is specific to my code, so I 'untabbed' the three lines specific to this code)

This is due to "hmget" here[3] being full of nulls and then attempting to call "Long::valueOf" on the null values.

[1] https://github.com/JPercivall/nifi/tree/BloomfilterProcessor
[2] https://github.com/Baqend/Orestes-Bloomfilter/blob/master/src/main/java/orestes/bloomfilter/redis/CountingBloomFilterRedis.java#L116 
```
java.lang.AssertionError: java.lang.NumberFormatException: null
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:193)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:152)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:147)
	at org.apache.nifi.util.StandardProcessorTestRunner.run(StandardProcessorTestRunner.java:142)
	at org.apache.nifi.processors.analysis.TestBloomFilter.testCountingBasic(TestBloomFilter.java:204)
	at org.apache.nifi.processors.analysis.integration.TestBloomFilterRedisBacked.testCountingBasic(TestBloomFilterRedisBacked.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.valueOf(Long.java:803)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.min(ReferencePipeline.java:520)
at orestes.bloomfilter.redis.CountingBloomFilterRedis.lambda$getEstimatedCount$9(CountingBloomFilterRedis.java:118)
at orestes.bloomfilter.redis.helper.RedisPool.safelyReturn(RedisPool.java:92)
at orestes.bloomfilter.redis.CountingBloomFilterRedis.getEstimatedCount(CountingBloomFilterRedis.java:115)
	at org.apache.nifi.processors.stateful.analysis.BloomFilterProcessor.onTrigger(BloomFilterProcessor.java:310)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:243)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:237)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JPercivall** [comment]
Actually this is a bigger issue than first thought. For reference, I am running against Redis 3.2.1. I inserted 300 values into the bloomfilter and then started running 700 checks (like the example in the  ReadMe) and still hit the NFE. 

Below is a screenshot of the variable values right before the stream command. It appears that hmget has the possibility to have null values strewn throughout the list (element 2 is null). 
![screen shot 2016-12-08 at 12 04 26 pm](https://cloud.githubusercontent.com/assets/11302527/21019335/0ed79f64-bd3e-11e6-81fb-f17592bac84d.png)

This could be a problem with Jedis but it would be nice to safely handle it within "Orestes-Bloomfilter".

**Comment by JPercivall** [comment]
Returning nulls here is part of the Jedis API: 

http://tool.oschina.net/uploads/apidocs/jedis-2.1.0/redis/clients/jedis/Jedis.html#hmget(java.lang.String, java.lang.String...)

**Comment by JPercivall** [comment]
PR opened here: https://github.com/Baqend/Orestes-Bloomfilter/pull/41

**Comment by edrabc** [comment]
In order to keep consistency between memory and redis storages, might be good to replace the ending `<Optional>.get();` with `<Optional>.orElse(0L)`:
```java
return hmget.stream().filter(Objects::nonNull).map(Long::valueOf).min(Comparator.<Long> naturalOrder()).orElse(0L);
```

After filtering null objects it could still throw a `NoSuchElementException` if all stream results are null:

```java
CountingBloomFilter<String> memory = new FilterBuilder().name("test").buildCountingBloomFilter();
System.out.println(memory.contains("test_key")); // false
System.out.println(memory.getEstimatedCount("test_key")); // 0

CountingBloomFilter<String> redis = new FilterBuilder().name("test").redisBacked(true).buildCountingBloomFilter();
System.out.println(redis.contains("test_key")); // false
System.out.println(redis.getEstimatedCount("test_key")); // java.util.NoSuchElementException: No value present
```

**Comment by JPercivall** [comment]
Good point @edrabc, I've updated my PR

**Comment by edrabc** [comment]
Thanks @JPercivall! Would be nice to have this PR merged soon.

**Comment by edrabc** [comment]
I did some tests of the Redis-Backed Counting Filter, comparing the previous implementation (+ capturing the `NumberFormatException`) and this new one filtering NULL values. The result is that most of the non-existing keys are false positives, as the real "zeroes" are removed and the min() operation fails to return the correct answer.

Looks like the solution would be to convert all NULL values from Redis to 0. I checked that false positives go back to normal with an implementation like:
```java
return hmget.stream().map(i -> (i != null) ? Long.valueOf(i) : 0L).min(Comparator.<Long> naturalOrder()).get();
```

**Comment by JPercivall** [comment]
Thanks for the review @edrabc, I've adjusted the logic to your implementation.

**Comment by fbuecklers** [comment]
Hi,

currently reviewing your pull request. When redis is completely empty. It will still raise an np or? because the stream is empty then wich cause get to return null.

Are you fine with this implementation?
```java
return hmget.stream().mapToLong(i -> i == null? 0L: Long.valueOf(i)).min().orElse(0L);
```

**Comment by fbuecklers** [comment]
It is fixed and released right now.

Regards
